spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sangiorgio
    username: root
    password: root6Beer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  access-key: "YOUR_AWS_ACCESS_KEY_ID"
  secret-key: "YOUR_AWS_SECRET_ACCESS_KEY"
  sqs:
    partial-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/partial-payment-queue
    full-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/full-payment-queue
    excess-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/excess-payment-queue