spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sangiorgio
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  sqs:
    partial-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/partial-payment-queue
    full-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/full-payment-queue
    excess-payment-queue: https://sqs.us-east-1.amazonaws.com/920372990680/excess-payment-queue